rootProject.name = 'SpringLegacy'
include 'common', 'api'
include 'services:user-service', 'services:account-service', 'services:work-service',
        'services:diagnosis-service', 'services:defense-service', 'services:payment-service',
        'services:notification-service', 'services:bff-service'
