dependencies {
    implementation project(':common')
    implementation "org.springframework:spring-webmvc:${springVersion}"
    implementation 'org.mybatis:mybatis-spring:2.1.2'
    implementation 'org.mybatis:mybatis:3.5.9'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}
