dependencies {
    implementation "org.springframework:spring-context:${springVersion}"
    implementation 'org.mybatis:mybatis:3.5.16'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.4'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}
